/**
 * 打印模板种子 JSON（与前端 agreePrintTemplate 对齐，mock 侧独立一份）
 */
export const BASE_AGREEMENT_PRINT_TEMPLATE = {
  panels: [
    {
      index: 0,
      name: 1,
      height: 297,
      width: 210,
      paperHeader: 28,
      paperFooter: 800,
      paperNumberLeft: 565,
      paperNumberTop: 819,
      paperNumberDisabled: false,
      paperNumberContinue: true,
      watermarkOptions: {},
      panelLayoutOptions: {},
      printElements: [
        {
          options: {
            left: 20,
            top: 20,
            height: 22,
            width: 550,
            title: '房屋征收补偿协议',
            fontSize: 18,
            fontWeight: '700',
            textAlign: 'center',
            lineHeight: 20,
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 52,
            height: 16,
            width: 260,
            title: '协议编号',
            field: 'agreementNo',
            fontSize: 10,
            testData: 'XY-2026-001',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 300,
            top: 52,
            height: 16,
            width: 260,
            title: '签约日期',
            field: 'signDate',
            fontSize: 10,
            testData: '2026-03-01',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 500,
            top: 18,
            height: 48,
            width: 48,
            field: 'qrcodeContent',
            textType: 'qrcode',
            qrcodeLevel: 1,
            hideTitle: true,
            testData: 'AGREE:XY-2026-001',
          },
          printElementType: { title: '二维码', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 74,
            height: 16,
            width: 260,
            title: '被征收人',
            field: 'compensatee',
            fontSize: 10,
            testData: '张三',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 300,
            top: 74,
            height: 16,
            width: 260,
            title: '征收人',
            field: 'acquirer',
            fontSize: 10,
            testData: '某区征收办',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 96,
            height: 16,
            width: 540,
            title: '协议名称',
            field: 'agreementName',
            fontSize: 10,
            testData: '某某项目征收补偿协议',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 124,
            height: 16,
            width: 200,
            title: '一、房屋明细',
            fontSize: 12,
            fontWeight: '600',
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 146,
            height: 54,
            width: 550,
            field: 'houses',
            tableHeaderRepeat: 'page',
            tableFooterRepeat: 'last',
            columns: [
              [
                {
                  title: '户名',
                  field: 'householdName',
                  width: 70,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '序号',
                  field: 'index',
                  width: 36,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '房屋地址',
                  field: 'address',
                  width: 120,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '产权证号',
                  field: 'certNo',
                  width: 80,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '房屋类型',
                  field: 'houseType',
                  width: 64,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '建筑面积',
                  field: 'buildArea',
                  width: 60,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '征收面积',
                  field: 'expropriatedArea',
                  width: 60,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '评估价值',
                  field: 'evalValue',
                  width: 60,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
              ],
            ],
          },
          printElementType: { title: '表格', type: 'table' },
        },
        {
          options: {
            left: 20,
            top: 230,
            height: 16,
            width: 200,
            title: '二、补偿安置',
            fontSize: 12,
            fontWeight: '600',
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 252,
            height: 54,
            width: 550,
            field: 'compensationItems',
            tableHeaderRepeat: 'page',
            tableFooterRepeat: 'last',
            columns: [
              [
                {
                  title: '序号',
                  field: 'index',
                  width: 42,
                  align: 'center',
                  colspan: 1,
                  rowspan: 2,
                  checked: true,
                },
                {
                  title: '项目信息',
                  field: '',
                  width: 220,
                  align: 'center',
                  colspan: 2,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '计价信息',
                  field: '',
                  width: 230,
                  align: 'center',
                  colspan: 3,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '备注',
                  field: 'remark',
                  width: 58,
                  align: 'left',
                  colspan: 1,
                  rowspan: 2,
                  checked: true,
                },
              ],
              [
                {
                  title: '项目名称',
                  field: 'name',
                  width: 130,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '计算方式',
                  field: 'calcType',
                  width: 90,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '数量',
                  field: 'quantity',
                  width: 70,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '单价',
                  field: 'unitPrice',
                  width: 80,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '金额',
                  field: 'amount',
                  width: 80,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  tableSummary: 'sum',
                },
              ],
            ],
          },
          printElementType: { title: '表格', type: 'table' },
        },
        {
          options: {
            left: 20,
            top: 340,
            height: 16,
            width: 200,
            title: '三、奖励补贴',
            fontSize: 12,
            fontWeight: '600',
            hideTitle: true,
            agreeVisibleWhen: 'hasRewards',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 362,
            height: 54,
            width: 550,
            field: 'rewardItems',
            tableHeaderRepeat: 'page',
            tableFooterRepeat: 'last',
            agreeVisibleWhen: 'hasRewards',
            columns: [
              [
                {
                  title: '序号',
                  field: 'index',
                  width: 42,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '奖励项目',
                  field: 'name',
                  width: 180,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '金额',
                  field: 'amount',
                  width: 120,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  tableSummary: 'sum',
                },
                {
                  title: '说明',
                  field: 'remark',
                  width: 208,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
              ],
            ],
          },
          printElementType: { title: '表格', type: 'table' },
        },
        {
          options: {
            left: 20,
            top: 450,
            height: 16,
            width: 540,
            title: '协议金额（小写）',
            field: 'amount',
            fontSize: 11,
            fontWeight: '600',
            testData: '760000',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 474,
            height: 16,
            width: 540,
            title: '协议金额（大写）',
            field: 'amountCn',
            fontSize: 11,
            fontWeight: '600',
            testData: '柒拾陆万元整',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 510,
            height: 16,
            width: 250,
            title: '被征收人签字：______________',
            fontSize: 10,
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 300,
            top: 510,
            height: 16,
            width: 250,
            title: '征收人盖章：______________',
            fontSize: 10,
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
      ],
    },
  ],
};

/**
 * 克隆模板并修改标题（用于附件一/二等种子）
 * @param title 纸面主标题
 */
export function clonePrintTemplateWithTitle(title: string) {
  const tpl = structuredClone(BASE_AGREEMENT_PRINT_TEMPLATE) as {
    panels: { printElements: { options?: { title?: string } }[] }[];
  };
  const head = tpl.panels?.[0]?.printElements?.[0]?.options;
  if (head) head.title = title;
  return tpl;
}
