/**
 * 协议打印默认模板（A4）
 * - 房屋表：户名 / 房屋类型支持运行时上下行合并（列上 agreeMergeSame）
 * - 评估价值 / 补偿金额等列用 agreeColFormat，合计仍按数字加总
 * - 签约日期默认 agreeFormat=date
 * - 补偿表：多级表头（列合并）
 * - 奖励区：agreeVisibleWhen=hasRewards，无奖励数据时不打印
 * - 页眉键值：agreeFlowGroup=header；同行缺一格则通栏，整行没了才上移
 * - 房屋/补偿/奖励：标题+表同组，整段隐藏后下方上移
 */
export const agreePrintTemplate = {
  panels: [
    {
      index: 0,
      name: 1,
      height: 297,
      width: 210,
      paperHeader: 28,
      paperFooter: 800,
      paperNumberLeft: 565,
      paperNumberTop: 819,
      paperNumberDisabled: false,
      paperNumberContinue: true,
      /** 空 content 表示关闭；设计器「水印」写入 hiprint watermarkOptions */
      watermarkOptions: { content: '' },
      panelLayoutOptions: {},
      printElements: [
        {
          options: {
            left: 20,
            top: 20,
            height: 22,
            width: 550,
            title: '房屋征收补偿协议',
            fontSize: 18,
            fontWeight: '700',
            textAlign: 'center',
            lineHeight: 20,
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 52,
            height: 16,
            width: 260,
            title: '协议编号',
            field: 'agreementNo',
            fontSize: 10,
            testData: 'XY-2026-001',
            agreeFlowGroup: 'header',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 300,
            top: 52,
            height: 16,
            width: 260,
            title: '签约日期',
            field: 'signDate',
            fontSize: 10,
            testData: '2026-03-01',
            agreeFormat: 'date',
            agreeFlowGroup: 'header',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 500,
            top: 18,
            height: 48,
            width: 48,
            field: 'qrcodeContent',
            textType: 'qrcode',
            qrcodeLevel: 1,
            hideTitle: true,
            testData: 'AGREE:XY-2026-001',
          },
          printElementType: { title: '二维码', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 74,
            height: 16,
            width: 260,
            title: '被征收人',
            field: 'compensatee',
            fontSize: 10,
            testData: '张三',
            agreeFlowGroup: 'header',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 300,
            top: 74,
            height: 16,
            width: 260,
            title: '征收人',
            field: 'acquirer',
            fontSize: 10,
            testData: '某区征收办',
            agreeFlowGroup: 'header',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 96,
            height: 16,
            width: 540,
            title: '协议名称',
            field: 'agreementName',
            fontSize: 10,
            testData: '某某项目征收补偿协议',
            agreeFlowGroup: 'header',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 124,
            height: 16,
            width: 200,
            title: '一、房屋明细',
            fontSize: 12,
            fontWeight: '600',
            hideTitle: true,
            agreeFlowGroup: 'houses',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 146,
            height: 54,
            width: 550,
            field: 'houses',
            tableHeaderRepeat: 'page',
            tableFooterRepeat: 'last',
            agreeFlowGroup: 'houses',
            /** 示例：仅打印评估价值大于 0 的行（可在设计器 options 修改） */
            agreeRowFilter: 'evalValue > 0',
            columns: [
              [
                {
                  title: '户名',
                  field: 'householdName',
                  width: 70,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  agreeMergeSame: true,
                },
                {
                  title: '序号',
                  field: 'index',
                  width: 36,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '房屋地址',
                  field: 'address',
                  width: 120,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '产权证号',
                  field: 'certNo',
                  width: 80,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '房屋类型',
                  field: 'houseType',
                  width: 64,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  agreeMergeSame: true,
                },
                {
                  title: '建筑面积',
                  field: 'buildArea',
                  width: 60,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '征收面积',
                  field: 'expropriatedArea',
                  width: 60,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '评估价值',
                  field: 'evalValue',
                  width: 60,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  tableSummary: 'sum',
                  agreeColFormat: 'money0',
                },
              ],
            ],
          },
          printElementType: { title: '表格', type: 'table' },
        },
        {
          options: {
            left: 20,
            top: 230,
            height: 16,
            width: 200,
            title: '二、补偿安置',
            fontSize: 12,
            fontWeight: '600',
            hideTitle: true,
            agreeFlowGroup: 'compensation',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 252,
            height: 54,
            width: 550,
            field: 'compensationItems',
            tableHeaderRepeat: 'page',
            tableFooterRepeat: 'last',
            agreeFlowGroup: 'compensation',
            /** 两行表头：项目信息 / 计价信息 做列合并 */
            columns: [
              [
                {
                  title: '序号',
                  field: 'index',
                  width: 42,
                  align: 'center',
                  colspan: 1,
                  rowspan: 2,
                  checked: true,
                },
                {
                  title: '项目信息',
                  field: '',
                  width: 220,
                  align: 'center',
                  colspan: 2,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '计价信息',
                  field: '',
                  width: 230,
                  align: 'center',
                  colspan: 3,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '备注',
                  field: 'remark',
                  width: 58,
                  align: 'left',
                  colspan: 1,
                  rowspan: 2,
                  checked: true,
                },
              ],
              [
                {
                  title: '项目名称',
                  field: 'name',
                  width: 130,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '计算方式',
                  field: 'calcType',
                  width: 90,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '数量',
                  field: 'quantity',
                  width: 70,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '单价',
                  field: 'unitPrice',
                  width: 80,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  agreeColFormat: 'money',
                },
                {
                  title: '金额',
                  field: 'amount',
                  width: 80,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  tableSummary: 'sum',
                  agreeColFormat: 'money',
                },
              ],
            ],
          },
          printElementType: { title: '表格', type: 'table' },
        },
        {
          options: {
            left: 20,
            top: 340,
            height: 16,
            width: 200,
            title: '三、奖励补贴',
            fontSize: 12,
            fontWeight: '600',
            hideTitle: true,
            /** 无奖励数据时整段不打印 */
            agreeVisibleWhen: 'hasRewards',
            agreeFlowGroup: 'rewards',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 362,
            height: 54,
            width: 550,
            field: 'rewardItems',
            tableHeaderRepeat: 'page',
            tableFooterRepeat: 'last',
            agreeVisibleWhen: 'hasRewards',
            agreeFlowGroup: 'rewards',
            columns: [
              [
                {
                  title: '序号',
                  field: 'index',
                  width: 42,
                  align: 'center',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '奖励项目',
                  field: 'name',
                  width: 180,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
                {
                  title: '金额',
                  field: 'amount',
                  width: 120,
                  align: 'right',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                  tableSummary: 'sum',
                  agreeColFormat: 'money',
                },
                {
                  title: '说明',
                  field: 'remark',
                  width: 208,
                  align: 'left',
                  colspan: 1,
                  rowspan: 1,
                  checked: true,
                },
              ],
            ],
          },
          printElementType: { title: '表格', type: 'table' },
        },
        {
          options: {
            left: 20,
            top: 450,
            height: 16,
            width: 540,
            title: '协议金额（小写）',
            field: 'amount',
            fontSize: 11,
            fontWeight: '600',
            testData: '760000',
            agreeFormat: 'money',
            agreeVisibleWhen: 'amount > 0',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 474,
            height: 16,
            width: 540,
            title: '协议金额（大写）',
            field: 'amountCn',
            fontSize: 11,
            fontWeight: '600',
            testData: '柒拾陆万元整',
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 20,
            top: 510,
            height: 16,
            width: 250,
            title: '被征收人签字：______________',
            fontSize: 10,
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
        {
          options: {
            left: 300,
            top: 510,
            height: 16,
            width: 250,
            title: '征收人盖章：______________',
            fontSize: 10,
            hideTitle: true,
          },
          printElementType: { title: '文本', type: 'text' },
        },
      ],
    },
  ],
};
